export const easyList = [
    "src/images/cat-1.jpg",
    "src/images/cat-1.jpg",
    "src/images/cat-10.jpg",
    "src/images/cat-10.jpg",
    "src/images/cat-3.jpg",
    "src/images/cat-3.jpg",
    "src/images/cat-4.jpeg",
    "src/images/cat-4.jpeg",
    "src/images/cat-5.jpg",
    "src/images/cat-5.jpg",
    "src/images/cat-6.jpg",
    "src/images/cat-6.jpg",
    "src/images/cat-7.jpg",
    "src/images/cat-7.jpg",
    "src/images/cat-8.jpg",
    "src/images/cat-8.jpg",
];

export const mediumList = [
    "src/images/cat-1.jpg",
    "src/images/cat-1.jpg",
    "src/images/cat-10.jpg",
    "src/images/cat-10.jpg",
    "src/images/cat-3.jpg",
    "src/images/cat-3.jpg",
    "src/images/cat-4.jpeg",
    "src/images/cat-4.jpeg",
    "src/images/cat-5.jpg",
    "src/images/cat-5.jpg",
    "src/images/cat-6.jpg",
    "src/images/cat-6.jpg",
    "src/images/cat-7.jpg",
    "src/images/cat-7.jpg",
    "src/images/cat-8.jpg",
    "src/images/cat-8.jpg",
    "src/images/cat-9.jpg",
    "src/images/cat-9.jpg",
    "src/images/cat-2.jpg",
    "src/images/cat-2.jpg",
    // "src/images/cat-11.jpg",
    // "src/images/cat-11.jpg",
    // "src/images/cat-16.jpg",
    // "src/images/cat-16.jpg",
];

export const hardList = [
    "src/images/cat-1.jpg",
    "src/images/cat-1.jpg",
    "src/images/cat-10.jpg",
    "src/images/cat-10.jpg",
    "src/images/cat-3.jpg",
    "src/images/cat-3.jpg",
    "src/images/cat-4.jpeg",
    "src/images/cat-4.jpeg",
    "src/images/cat-5.jpg",
    "src/images/cat-5.jpg",
    "src/images/cat-6.jpg",
    "src/images/cat-6.jpg",
    "src/images/cat-7.jpg",
    "src/images/cat-7.jpg",
    "src/images/cat-8.jpg",
    "src/images/cat-8.jpg",
    "src/images/cat-9.jpg",
    "src/images/cat-9.jpg",
    "src/images/cat-13.jpg",
    "src/images/cat-13.jpg",
    "src/images/cat-11.jpg",
    "src/images/cat-11.jpg",
    "src/images/cat-12.jpg",
    "src/images/cat-12.jpg",
    // "src/images/cat-13.jpg",
    // "src/images/cat-13.jpg",
    // "src/images/cat-14.jpg",
    // "src/images/cat-14.jpg",
    // "src/images/cat-15.jpg",
    // "src/images/cat-15.jpg",
    // "src/images/cat-16.jpg",
    // "src/images/cat-16.jpg",
];
